'use strict';
/**
 * One-off build script: downloads the Plus Jakarta Sans latin subsets and
 * self-hosts them in public/fonts so the site makes ZERO third-party requests
 * at runtime. Committed output: public/fonts/*.woff2 + public/fonts/fonts.css
 *
 * Run once: node scripts/fetch-fonts.js
 */

const fs = require('fs');
const path = require('path');

const OUT = path.resolve(__dirname, '..', 'public', 'fonts');
const WEIGHTS = [400, 500, 600, 700, 800];
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const rules = [];

  for (const w of WEIGHTS) {
    const url = `https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@${w}&display=swap`;
    const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

    // Each subset is written as:  /* subset-name */  @font-face { ... }
    // Parse the pairs directly — the comment belongs to the block that follows it.
    const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
    let latin = null;
    let m;
    while ((m = re.exec(css))) {
      if (m[1] === 'latin') latin = m[2];
    }
    if (!latin) {
      console.warn(`  ! no latin subset for weight ${w}`);
      continue;
    }
    const urlMatch = latin.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!urlMatch) {
      console.warn(`  ! no woff2 url for weight ${w}`);
      continue;
    }
    const range = (latin.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';

    const buf = Buffer.from(await (await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })).arrayBuffer());
    const file = `plus-jakarta-sans-${w}.woff2`;
    fs.writeFileSync(path.join(OUT, file), buf);
    console.log(`  ✓ ${file}  ${(buf.length / 1024).toFixed(1)} KB`);

    rules.push(
      `@font-face{font-family:'Plus Jakarta Sans';font-style:normal;font-weight:${w};font-display:swap;` +
        `src:url('/fonts/${file}') format('woff2');` +
        (range ? `unicode-range:${range.trim()};` : '') +
        `}`
    );
  }

  fs.writeFileSync(
    path.join(OUT, 'fonts.css'),
    `/* Self-hosted — generated by scripts/fetch-fonts.js. Do not edit by hand. */\n` +
      rules.join('\n') +
      '\n'
  );
  console.log(`\nWrote ${rules.length} @font-face rules to public/fonts/fonts.css`);
}

main().catch((e) => {
  console.error('Font fetch failed:', e.message);
  process.exitCode = 1;
});
